version: '2'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "54320:5432"

  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "33060:3306"

  oracle:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - "49160:22"
      - "49161:1521"
